[package]
name = "drawing-bord"
version = "0.1.0"
authors = ["Septias <39526136+Septias@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"